Repository DeveloperAcademy-POSTECH/MacC-TEAM-8bit, pull requests merged in 2022-12, with the labels that each got.

#329 [#226] 루트파인팅 포인트 삭제
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/activated_foot_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/activated_foot_button.imageset/activated foot button.svg
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/activated_hand_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/activated_hand_button.imageset/activated hand button.svg
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/deactivated_foot_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/deactivated_foot_button.imageset/deactivated foot button.svg
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/deactivated_hand_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/deactivated_hand_button.imageset/deactivated hand button.svg
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/delete_destructive.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/delete_destructive.imageset/test.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/foot_point_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/foot_point_button.imageset/foot_point_button.svg
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/hand_point_button.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/RouteFinding/hand_point_button.imageset/hand_point_button.svg
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureFootButton.swift
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureHandButton.swift
  OrrRock/OrrRock/Utils/CustomPanGestureRecognizer.swift
Labels: feat, 🍒Yeni

#328 [#314] feat - 기기간 뷰 레이아웃 대응
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController+UICollectionViewExtensions.swift .swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewCell.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewFlowLayout.swift
Labels: feat, 👾Kkoma

#327 [#321] fix - del 버튼 연타 방지 및 오류수정
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 🧸Ruyha

#331 [#330] style - push하지 않은 수정 커밋 재 PR
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewFlowLayout.swift
Labels: chore, 👾Kkoma

#341 [#337] fix - 루트파인딩 디테일에서 뒤로 나가면 하단 툴바 자리가 남아있는 문제 개선
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
Labels: fix, 🌝Dodo

#342 [#338] feat - 루트파인딩 화면 내 이미지 화질 개선
  OrrRock/OrrRock/Extensions/String+.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
Labels: feat, 🎵EllyJ

#343 [#233] feat - 루트파인딩 온보딩 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/RouteFindingOnboardingHandImage.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/RouteFindingOnboardingHandImage.imageset/info-image.png
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController+UICollectionViewExtensions.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewCell.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFifthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFirstOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFourthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingOnboardingParentViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingOnboardingViewController+UIPageViewExtensions.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSecondOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSeventhOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSixthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingThirdOnboardingViewController.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: feat, 💡LED

#347 [#334] feat - 루트파인딩 디테일뷰 내 정보 뷰 표시 등의 제스처 구현
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController+GestureExtensions.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
Labels: feat, 🎵EllyJ

#346 [#335] style - 루트파인딩 디테일 뷰 Sketch 디자인 반영
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteViewController.swift
Labels: style, 💡LED

#348 [#345] fix - 루트파인딩 메인뷰 새로운 루트파인딩 추가시 에러 해결 + 색상 변경
  OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewCustomCell.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewHeaderCell.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
Labels: fix, 🌝Dodo

#349 [#332] feat - gesture 관련 추가 작업
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageViewController.swift
  OrrRock/OrrRock/Utils/CustomPanGestureRecognizer.swift
Labels: 🍒Yeni

#361 [#352] - fix 루트파인딩 업로드 카메라 뷰 배경 삽입
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: fix, 🎵EllyJ

#360 [#353] feat - infoview가 나와있으면 페이지 전환을 하지못하게 바꾸었습니다.
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController+Extensions.swift
Labels: feat, 🌝Dodo

#366 [#357] fix - 루트파인딩 메인 뷰 썸네일과 detailView 컨텐츠 불일치
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
Labels: fix, 🌝Dodo

#365 [#355] fix - tabbar color 를 변경하였습니다.
  OrrRock/OrrRock/AppDelegate.swift
Labels: fix, 🌝Dodo

#364 [#350] feat - 루트파인딩 저장하기 뷰 내 디테일 수정
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
Labels: feat, 👾Kkoma

#362 [#356] fix - 루트파인딩 기능 뷰 내 X 버튼의 Alert 추가
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
Labels: fix, 🎵EllyJ

#371 [#359] fix - 루트파인딩 디테일 페이지 수, 썸네일 수 불일치 개선
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingDetail/RoutefindingDetailViewController+UIPageViewControllerExtensions.swift
Labels: fix, 🎵EllyJ

#370 [#367] fix - 루트 파인딩 메인뷰 바텀 옵션뷰 높이 이슈
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
Labels: fix, 🌝Dodo

#373 [#358] feat - 루트파인딩 온보딩 제스쳐 반영 및 기타 수정
  OrrRock/OrrRock/Home/Cell/HomeCardCollectionViewThumbnailCell.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewListCell.swift
  OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewCustomCell.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewCell.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFifthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFirstOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFourthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingOnboardingParentViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSecondOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSeventhOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSixthOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingThirdOnboardingViewController.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewCell.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoPlayView.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/Cell/VideoCollectionViewCustomCell.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoPlayViewController/VideoPlayViewController.swift
Labels: feat

#363 [#354] fix -루트파인딩 삭제 관련 워딩 수정
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5.png
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
  OrrRock/OrrRock/Home/Cell/HomeCollectionViewHeaderCell.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFirstOnboardingViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/Cell/VIdeoCollectionFooterCell.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift
Labels: fix, 🎵EllyJ

#376 [#375] chore - 1.2.0 릴리즈 버전 관리
  OrrRock/OrrRock.xcodeproj/project.pbxproj
Labels: chore, 🎵EllyJ

#385 [#384] design - RouteFinding X 버튼 SFSymbol로 교체
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: design, 🎵EllyJ

#383 [#380] fix - 로고 이미지 에셋 수정
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock_logo 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock_logo.png
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
Labels: fix, asset

#389 [#381] fix - 토스트 스피드 수정
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
Labels: fix, 🌝Dodo

#390 [#388] design - 스와이프 카드 뷰 레이아웃 및 디자인 변경
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Utils/NewLevelPickerView.swift
Labels: design, 💡LED

#391 [#386] release - 1.2.1 릴리즈 버전 관리
  OrrRock/OrrRock.xcodeproj/project.pbxproj
Labels: Release

#398 Release 1.2.1
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock_logo 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock_logo.png
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingFirstOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingOnboarding/RouteFindingSeventhOnboardingViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFifthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Utils/NewLevelPickerView.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController+Extensions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: Release

#395 [#394] feat - 레벨 이미지 롱프레스시 저장 및 공유기능
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MyActivity/MyActivityViewController+Extensions.swift
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/MyCardView+Protocol.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/MyCardView.swift
  OrrRock/OrrRock/Utils/HapticManager.swift
Labels: feat, 🌝Dodo

#397 [#396] fix-각종 버그 수정 및 개선
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/BlockView.swift
Labels: fix, 🧸Ruyha

#402 [#399] release - 1.2.2 릴리즈 버전 관리
  OrrRock/OrrRock.xcodeproj/project.pbxproj
Labels: Release

#403 [#172] doc - 리드미 작성
  README.md
Labels: doc, 👾Kkoma

#404 Release 1.2.2
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MyActivity/MyActivityViewController+Extensions.swift
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/MyCardView+Protocol.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/MyCardView.swift
  OrrRock/OrrRock/RouteFindingDetail/RouteFindingDetailViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/BlockView.swift
  OrrRock/OrrRock/Utils/HapticManager.swift
  README.md
Labels: Release
