Repository DeveloperAcademy-POSTECH/MacC-TEAM-8bit, pull requests merged in 2022-11, with the labels that each got.

#95 [#94] fix PHPicker의 선택한 사진 으로 앱 사용시 발생하는 문제점 대응
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/UploadModels/GymSettingModel.swift
  OrrRock/OrrRock/Ruyha/UpoadTestNextViewController.swift
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: fix, 🧸Ruyha

#113 [#112] hotfix 권한 요청 문구 수정 및 빌드 번호 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Info.plist
  OrrRock/OrrRock/Models/UploadModels/GymSettingModel.swift
Labels: hotfix

#114 [#101] fix - 피드백 글자와 날짜 정보 겹쳐짐
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
Labels: fix, 👾Kkoma

#115 [#103] fix - 레벨 설정 버튼이 제대로 잘 눌리지 않는 불편함을 개선했습니다.
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
Labels: fix, 🦒Ian

#117 [#100] fix 썸네일 깨지는 문제 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/String+.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/Views/HomeView/HomeCardCollectionViewThumbnailCell.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
Labels: fix, 🧸Ruyha

#118 [#102] fix 영상테두리추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/UploadModels/SwipeableCardModel/SwipeableCardVideoModel.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
Labels: fix, 🧸Ruyha

#120 [#97, #99, #107, #108, #109, #110] fix - VideoCollectionView ,Detail View관련 버그 + 유저피드백 반영
  OrrRock/OrrRock/Assets.xcassets/dummy/image/Check.imageset/Check.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/Check.imageset/Contents.json
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
Labels: fix, 🌝Dodo

#119 [#106] fix - 영상 분류 완료 로직 개선
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
Labels: fix, 👾Kkoma

#122 [#121] fix - 영상이 삭제된 경우에 VideoDetailView 예외처리
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
Labels: fix, 💡LED

#125 [#123] fix - 영상 삭제 버그 해결
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
Labels: fix, 🌝Dodo

#127 [#104] fix Default 문제 레벨 설정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/UIview+.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/LevelPickerView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
Labels: fix, 🧸Ruyha

#130 [#129] fix 홈화면 목록형으로 볼때 썸네일 깨짐 수정
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
Labels: fix, 🧸Ruyha

#128 [#126] fix onboarding view
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/dummy/image/Light.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/Light.imageset/Light.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage1.imageset/OnboardingImage1.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage2.imageset/OnboardingImage2.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage3.imageset/OnboardingImage3.png
  OrrRock/OrrRock/Base.lproj/LaunchScreen.storyboard
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewController.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewControllerFirst.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewControllerSecond.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewControllerThird.swift
Labels: fix, 🌝Dodo

#131 [#105] fix - 스와이프 뷰 버그 수정 및 로직 개선
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Utils/ButtonClickEffect.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
Labels: fix, 👾Kkoma

#133 [#132] hotfix 슬로우모션 비디오 업로드 제한
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: hotfix, 🧸Ruyha

#138 [#135] refactor - 레드 코드 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Extension
  OrrRock/OrrRock/Models/Model
  OrrRock/OrrRock/Models/VideoFilterEnum.swift
  OrrRock/OrrRock/Resources/Resource
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/ViewControllers/ViewController
  OrrRock/OrrRock/Views/HomeView/HomeCardCollectionViewThumbnailCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell+CollectionViewExtensions.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewFooterCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewHeaderCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
Labels: refactor, 💡LED

#137 [#135] refactor - 코드 인덴트 및 안쓰는 코드 수정
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewControllerFirst.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/DateAndGymEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+DataSorting.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/Views/VideoCollectionView/BasePaddingLabel.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
Labels: refactor, 🌝Dodo

#136 [#135] refactor - 코드 정리 및 주석 삭제, 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Button+.swift
  OrrRock/OrrRock/Extensions/Color+.swift
  OrrRock/OrrRock/Extensions/Padding+.swift
  OrrRock/OrrRock/Extensions/UIView+.swift
  OrrRock/OrrRock/Models/UploadModels/GymSettingModel.swift
  OrrRock/OrrRock/Models/UploadModels/SwipeableCardModel/SwipeableCardVideoModel.swift
  OrrRock/OrrRock/Utils/CustomIndicator.swift
  OrrRock/OrrRock/Utils/UnderlinedTextField.swift
  OrrRock/OrrRock/Views/UploadView/DateSettingViewController.swift
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: refactor, 🧸Ruyha

#140 [#135] refactor - 코드 정리 및 주석 삭제, 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Utils/ButtonClickEffect.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/DummyData/DummyVideoModel.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
Labels: refactor, 👾Kkoma

#139 [#135] refactor - 코드 인덴트 수정 및 사용하지 않는 코드 제거
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/AppDelegate.swift
  OrrRock/OrrRock/Models/CoreData/CoreDataDAO.swift
  OrrRock/OrrRock/Models/CoreData/DataManager.swift
  OrrRock/OrrRock/Models/CoreData/DataRepository.swift
  OrrRock/OrrRock/Models/CoreData/RandomDataGenerator.swift
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataClass.swift
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataProperties.swift
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController+.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
Labels: refactor, 🎵EllyJ

#143 [fix] #134 레벨 라벨이 카드 위로 올라오는 문제해결
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Button+.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 🧸Ruyha

#146 [#145] fix add DateSettingView nextButton bottom padding
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
Labels: 🧸Ruyha

#169 [#147] fix LevelAndPFSettingViewController 오토레이아웃 수정
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 🧸Ruyha

#170 [#165] fix - request가 불가능한 영상이 들어왔을 경우 경고창과 함께 뒤로 돌아가는 로직 구현
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 👾Kkoma

#176 [#155] fix - 레벨 선택 피커 사용성 개선
  OrrRock/OrrRock/Upload/UIComponent/View/LevelPickerView.swift
Labels: fix, 💡LED

#175 [#151] feat - UploadView 내 클라이밍장 이름 입력 시 최근 방문 이름 및 이름 자동완성 기능 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/Icons/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Icons/location icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Icons/location icon.imageset/location icon.svg
  OrrRock/OrrRock/CoreData/CoreDataDAO.swift
  OrrRock/OrrRock/CoreData/DataManager.swift
  OrrRock/OrrRock/CoreData/DataRepository.swift
  OrrRock/OrrRock/CoreData/VisitedClimbingGym+CoreDataClass.swift
  OrrRock/OrrRock/CoreData/VisitedClimbingGym+CoreDataProperties.swift
  OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
  OrrRock/OrrRock/Upload/Cell/AutocompleteTableViewCell.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController+TableViewExtensions.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/VideoDetail/DateAndGymEditViewController+TableViewExtensions.swift
  OrrRock/OrrRock/VideoDetail/DateAndGymEditViewController.swift
Labels: feat, 💡LED

#177 [#171] feat - 영상이 백그라운드에서 재생 정지된 채 로드되고 상단 노출 되었을 때 재생되는 기능 추가
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
Labels: feat, 👾Kkoma

#178 [#150, #153, #157, #159] fix - UT 반영 사용성 개선
  OrrRock/OrrRock/Home/Cell/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewController.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/LevelPickerView.swift
  OrrRock/OrrRock/VideoDetail/DateAndGymEditViewController.swift
  OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
  OrrRock/OrrRock/VideoDetail/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController.swift
Labels: fix, 💡LED

#174 [#147] fix 온보딩 오토레이아웃 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/LaunchScreen/Contents.json
  OrrRock/OrrRock/Assets.xcassets/LaunchScreen/Light.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/LaunchScreen/Light.imageset/Light.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/Contents.json
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage1.imageset/Group 2.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage1.imageset/Group 3.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage1.imageset/Group 4.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage2.imageset/Group 3 2.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage2.imageset/Group 3 3.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage2.imageset/Group 3 4.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage3.imageset/Group 3.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage3.imageset/Group 4.png
  OrrRock/OrrRock/Assets.xcassets/OnboardingImages/OnboardingImage3.imageset/Group 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/Check.imageset/Check.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/Check.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage1.imageset/OnboardingImage1.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage2.imageset/OnboardingImage2.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/OnboardingImage3.imageset/OnboardingImage3.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/gorilla.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/gorilla.imageset/gorilla.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon1.imageset/􀢾.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon2.imageset/icon2.png
  OrrRock/OrrRock/OnBoarding/OnBoardigSuperViewController.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewController.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewControllerFirst.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewControllerSecond.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewControllerThird.swift
Labels: fix, 🧸Ruyha

#181 [#180] fix - 영상삭제시 버그 해결
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoDetail/VideoCollectionViewController.swift
Labels: fix, 🌝Dodo

#182 [#179] feat - 스와이프온보딩, 스와이프뷰 이미지 추가
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/스와이프온보딩1 3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/스와이프온보딩1 5.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/스와이프온보딩1 6.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/스와이프온보딩2 4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/스와이프온보딩2 5.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/스와이프온보딩2 6.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/스와이프온보딩3 3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/스와이프온보딩3 4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/스와이프온보딩3 5.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/스와이프온보딩4 3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/스와이프온보딩4 4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/스와이프온보딩4 5.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/스와이프온보딩5 3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/스와이프온보딩5 4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/스와이프온보딩5 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/실패화살표 3.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/실패화살표 4.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/실패화살표 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/실패아이콘 3.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/실패아이콘 4.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/실패아이콘 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/성공화살표 3.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/성공화살표 4.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/성공화살표 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/성공아이콘 2.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/성공아이콘 5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/성공아이콘 6.png
Labels: asset, 🧸Ruyha

#183 [#179] fix - 이전 PR 오류수정
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/SwipeOnboardingImages5 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/SwipeOnboardingImages5 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImages5.imageset/SwipeOnboardingImages5.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/fail_arrow 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/fail_arrow 2.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_arrow.imageset/fail_arrow.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/fail_icon 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/fail_icon 2.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_icon.imageset/fail_icon.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/success_arrow 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/success_arrow 2.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_arrow.imageset/success_arrow.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/success_icon 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/success_icon 2.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_icon.imageset/success_icon.png
Labels: fix, 🧸Ruyha

#187 [#152] fix - VideoCollectionView 하트 이미지 위치 조절
  OrrRock/OrrRock/VideoDetail/Cell/VideoCollectionViewCustomCell.swift
Labels: fix, 🌝Dodo

#190 [#154,#167] VideoDetailView 제스쳐 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoCollection/Cell/VIdeoCollectionFooterCell.swift
  OrrRock/OrrRock/VideoCollection/Cell/VideoCollectionViewCustomCell.swift
  OrrRock/OrrRock/VideoCollection/Cell/VideoCollectionViewHeaderCell.swift
  OrrRock/OrrRock/VideoCollection/Label/BasePaddingLabel.swift
  OrrRock/OrrRock/VideoCollection/VideoCollectionView+DataSorting.swift
  OrrRock/OrrRock/VideoCollection/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/VideoCollection/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController+Extensions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController.swift
Labels: feat, 🌝Dodo

#188 [#163] fix - 스와이프 감도 향상
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix

#192 [#166] feat - 영상 스와이프 뷰에서 총 영상 개수와 남은 영상 개수 띄워주는 작업
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
Labels: feat, 👾Kkoma

#191 [#189] design - HomeView UI 수정
  OrrRock/OrrRock/Home/Cell/HomeTableViewHeader.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
Labels: design, 💡LED

#194 [#156] fix - Back Button 반응 영역 개선
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/CustomBackBarButtomItem.swift
  OrrRock/OrrRock/VideoCollection/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController.swift
Labels: fix, 💡LED

#197 [#195] fix - HomeView 내 Thumbnail 관련 UI 수정
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell+CollectionViewExtensions.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
Labels: fix

#200 [#179] fix - 스와이프 온보딩 작업 완료
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5.png
  OrrRock/OrrRock/Extensions/Color+.swift
  OrrRock/OrrRock/Extensions/UIImageView+.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/EmptyBackgroundView.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFifthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingViewController.swift
Labels: fix

#204 [#203] hotfix 컬러,패딩 변경에 따른 대응값 수정
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/SwipeOnboarding/EmptyBackgroundView.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFifthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
Labels: hotfix, 🧸Ruyha

#205 [#193] feature - 좌우 스와이프 화면 이동
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoCollection/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoDetailPageViewController+Extentions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoDetailPageViewController+Protocol.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoDetailPageViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoPlayViewController/VideoPlayViewController+Extensions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoPlayViewController/VideoPlayViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController+Extensions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController+Protocol.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: feat, 🌝Dodo

#209 [#208] fix - 목록형 뷰에서 셀 선택시 나오던 에러 해결
  OrrRock/OrrRock/Home/HomeViewController+CollectionViewExtensions.swift
Labels: fix, 🌝Dodo

#207 [#96] feat - 영상 재생 시점 변경을 위한 Video Slider를 구현했습니다.
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/sliderThumb.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/sliderThumb.imageset/sliderBar.svg
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/VideoSlider.swift
Labels: 🍒Yeni

#212 [#211] fix - 리스트형 제스쳐 기능추가 + 메모리 관리
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoPlayViewController/VideoPlayViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController+Extensions.swift
Labels: fix, 🌝Dodo

#235 [#234] hotfix - Release 버전 관리를 위한 UINavigationViewController root뷰 수정
  OrrRock/OrrRock/SceneDelegate.swift
Labels: hotfix, 🎵EllyJ

#228 [#215, #217] design - 날짜, 클라이밍장 정보 입력, 편집 UI 수정 + 기타 기능 수정
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Utils/CustomBackBarButtomItem.swift
  OrrRock/OrrRock/Utils/UnderlinedTextField.swift
  OrrRock/OrrRock/VideoDetail/DateAndGymEditViewController.swift
Labels: design

#229 [#214] feat - 영상 정보 날짜, 클라이밍장 수정 로직 분리
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/CoreDataDAO.swift
  OrrRock/OrrRock/CoreData/DataManager.swift
  OrrRock/OrrRock/CoreData/DataRepository.swift
  OrrRock/OrrRock/VideoDetail/DateEditViewController.swift
  OrrRock/OrrRock/VideoDetail/GymEditViewController+TableViewExtensions.swift
  OrrRock/OrrRock/VideoDetail/GymEditViewController.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
Labels: feat

#239 [#218] fix - VideoDetailView toolbar UI 변경
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 🌝Dodo

#231 [#201] feat - 커스텀 레벨 피커 제작
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Font+.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/Utils/NewLevelPickerView.swift
Labels: feat, 🧸Ruyha

#243 [#220] design - VideoDetailView 내부의 edit view 수정
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_select.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/fail_select.imageset/fail_select.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_select.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/success_select.imageset/success_select.png
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/LevelPickerView.swift
  OrrRock/OrrRock/Utils/UnderlinedTextField.swift
  OrrRock/OrrRock/VideoDetail/DateEditViewController.swift
  OrrRock/OrrRock/VideoDetail/GymEditViewController.swift
  OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
Labels: design, 🌝Dodo

#245 [#244] design - delete searchTable
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoDetail/GymEditViewController+TableViewExtensions.swift
  OrrRock/OrrRock/VideoDetail/GymEditViewController.swift
Labels: design, 🌝Dodo

#246 [#238] feat 스와이프 온보딩 버그 수정 및 적용
  OrrRock/OrrRock/Extensions/String+.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFifthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/NewLevelPickerView.swift
Labels: feat, 🧸Ruyha

#251 [#250] feat 컬러피커 제작완료
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Utils/ColorPickerView.swift
  OrrRock/OrrRock/Utils/TestColorPickerViewController.swift
Labels: feat, 🧸Ruyha

#253 [#237] Feat 커스텀 피커 적용완료
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: feat, asset, 🧸Ruyha

#252 [#249] design - HomeView 린다 디자인 피드백 반영 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/UIImage+.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewCardCell.swift
  OrrRock/OrrRock/Home/Cell/HomeTableViewListCell.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
Labels: design, 💡LED

#255 [#254] fix - 레벨 수정 뷰 기기대응
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
Labels: fix, 🌝Dodo

#258 [#230] feat - 공유를 위한 영상에 이미지 추가하여 export 하는 기능 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/ORRROCK.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/ORRROCK.imageset/ORRROCK.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/calandarIcon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/calandarIcon.imageset/calandarIcon.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/gradation.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/gradation.imageset/gradation.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/gymIcon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/gymIcon.imageset/gymIcon.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V0.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V0.imageset/V0.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V1.imageset/V1.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V2.imageset/V2.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V3.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V3.imageset/V3.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V4.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V4.imageset/V4.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V5.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V5.imageset/V5.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V6.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V6.imageset/V6.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V7.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V7.imageset/V7.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V8.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V8.imageset/V8.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V9.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holder/V9.imageset/V9.png
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V0_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V1_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V2_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V3_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V4_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V5_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V6_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V7_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V8_Color.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/ExportVideo/holderColor/V9_Color.colorset/Contents.json
  OrrRock/OrrRock/Extensions/Color+.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/ColorPickerView.swift
  OrrRock/OrrRock/Utils/TestColorPickerViewController.swift
  OrrRock/OrrRock/VideoDetail/ExportViewController.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoPlayView.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: feat, 👾Kkoma

#257 [#256] fix - MyActivityView 진입 시 3개 이하의 데이터일 때 앱 크래시 수정
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/HomeGymChartView.swift
Labels: fix, 💡LED

#260 [#213] feat - 영상 삭제 로직 및 버튼 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/delete.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/delete.imageset/KakaoTalk_Photo_2022-11-23-17-22-34.png
  OrrRock/OrrRock/CoreData/VideoInfo.swift
  OrrRock/OrrRock/Extensions/UIImageView+.swift
  OrrRock/OrrRock/Models/Enums/SwipeableCardVideoModel.swift
  OrrRock/OrrRock/Models/Enums/VideoResultType.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
Labels: feat, 🍒Yeni

#267 [#223] feat - 루트파인딩 메인페이지의 데이터 구조 설계 및 DataManager 함수 작성
  OrrRock/Model.xcdatamodeld/Model.xcdatamodel/contents
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/RouteFinding/FootOrHand.swift
  OrrRock/OrrRock/CoreData/RouteFinding/ForceDirection.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PageInfo.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PageInformation+CoreDataClass.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PageInformation+CoreDataProperties.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PointInfo.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PointInformation+CoreDataClass.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PointInformation+CoreDataProperties.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteInfo.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteInformation+CoreDataClass.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteInformation+CoreDataProperties.swift
  OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
Labels: feat, 🎵EllyJ

#265 [#264] fix - 컬러피커뷰의 선택 상태 개선을 했습니다.
  OrrRock/OrrRock/Utils/ColorPickerView.swift
Labels: fix, 🧸Ruyha

#270 [#268] fix - RouteFindingDataManager RouteInformation 데이터 수정 메소드 분리
  OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
Labels: fix, 🎵EllyJ

#269 [#241] fix 앱의 전체적인 부분에서 뒤로가기 버튼 및 뒤로가기 제스쳐 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/UINavigationController+.swift
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingViewController.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Utils/CustomBackBarButtomItem.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 🧸Ruyha

#272 [#225] feat - 루트파인딩 기능 뷰 UI 및 페이징 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/DataManager.swift
  OrrRock/OrrRock/Info.plist
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController+UICollectionViewExtensions.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageView.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewCell.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewFlowLayout.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: feat, 💡LED

#274 [#225] fix - PR 코드리뷰 반영 코드 수정
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageView.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewCell.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingThumbnailCollectionViewFlowLayout.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: fix

#273 [#221] feat - 루트파인딩의 메인페이지 UI구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/Symbols/selectable_icon.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/selectable_icon.imageset/Ellipse 3.png
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/Models/Enums/RouteFindingCollectionViewMode.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewCustomCell.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewHeaderCell+Protocol.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewHeaderCell.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController+Extensions.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteModalViewController+Protocol.swift
  OrrRock/OrrRock/RouteFinding/RouteModalViewController.swift
  OrrRock/OrrRock/Utils/ImageButton.swift
  OrrRock/OrrRock/Utils/UnderlineSegmentedControl.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/Label/BasePaddingLabel.swift
Labels: feat, 🌝Dodo

#281 [#280] feat - RouteDataManager 도전 상태 변경 메소드 구현
  OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
Labels: feat, 🎵EllyJ

#283 [#282] hotfix - 오류 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
Labels: hotfix, 🧸Ruyha

#286 [#284] fix 상단 여백 발생 이슈 및 하단 탭바 영역 이슈 해결
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/MyActivity/MyActivityViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 🧸Ruyha

#285 [#224] feat - 루트파인딩 이미지 추가 UI, 로직 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray900.colorset/Contents.json
  OrrRock/OrrRock/Extensions/UIImage+.swift
  OrrRock/OrrRock/Models/Enums/CameraSessionStatus.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+AVCapturePhotoCaptureDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/TEST/ImageViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/TEST/RouteFindinCameraViewController+.swift
  OrrRock/OrrRock/RouteFindingUpload/UIComponent/CameraView.swift
Labels: feat, 🎵EllyJ

#292 [#289] fix - RouteFindingCameraViewController 오류 수정
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+AVCapturePhotoCaptureDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: fix, 🎵EllyJ

#291 [#288] fix - 영상 편집 화면의 레벨 피커 적용
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Utils/NewLevelPickerView.swift
  OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
Labels: fix, 🧸Ruyha

#290 [#222] feat - 루트파인딩 메인뷰 코어데이터 연결 + refactoring
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/AppDelegate.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
  OrrRock/OrrRock/Extensions/Date+.swift
  OrrRock/OrrRock/Models/Enums/RouteFindingEditType.swift
  OrrRock/OrrRock/Models/Enums/RouteFindingSection.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewCustomCell.swift
  OrrRock/OrrRock/RouteFinding/Cell/RouteFindingCollectionViewHeaderCell.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteModalViewController.swift
Labels: feat, refactor, 🌝Dodo

#300 [#299] feat - RouteFindingCameraViewController 연결
  OrrRock/OrrRock/RouteFinding/RouteFindingMainViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: feat, 🌝Dodo

#301 [#298] feat - RouteFinding Camera - Feature View Controller 연결하기
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+AVCapturePhotoCaptureDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/TEST/ImageViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/TEST/RouteFindinCameraViewController+.swift
Labels: feat, 🎵EllyJ

#294 [#293] fix 컬러피커뷰 백그라운드 적용 완료
  OrrRock/OrrRock/Utils/ColorPickerView.swift
  OrrRock/OrrRock/VideoDetail/ExportViewController.swift
Labels: fix, 🧸Ruyha

#302 [#227] feat - 루트파인딩 저장하기 UI 및 로직 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataManager.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+AVCapturePhotoCaptureDelegate.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingGymSaveViewController+TableViewExtention.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingGymSaveViewController.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingLevelSaveViewController.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController+UICollectionViewExtensions.swift .swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewCell.swift
  OrrRock/OrrRock/SaveRootFinding/saveRouteFindingImageCollectionViewFlowLayout.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: feat, 👾Kkoma

#306 [#304] hotfix - 변수명 수정 및 필요없는 코드 삭제
  OrrRock/OrrRock/SaveRootFinding/RouteFindingGymSaveViewController.swift
Labels: hotfix, 👾Kkoma

#303 [#295] fix 스와이프 온보딩 이미지 변경 및 스킵 버튼 위치 수정
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage1.imageset/SwipeOnboardingImage1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage2.imageset/SwipeOnboardingImage2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage3.imageset/SwipeOnboardingImage3.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage4.imageset/SwipeOnboardingImage4.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImage5.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5 2.png
  OrrRock/OrrRock/Assets.xcassets/SwipeOnboardingImages/SwipeOnboardingImage5.imageset/SwipeOnboardingImages5.png
  OrrRock/OrrRock/Extensions/String+.swift
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFirstViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingFourthViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingSecondViewController.swift
  OrrRock/OrrRock/SwipeOnboarding/SwipeOnboardingThirdViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 🧸Ruyha

#308 [#307] hotfix 오류수정
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: hotfix, style, 🧸Ruyha

#312 [#311] fix - 토스트 메세지의 스피드를 조절하였습니다.
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController+Extensions.swift
Labels: fix, 🌝Dodo

#310 [#305] fix UX writing 수정
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Home/HomeViewController.swift
  OrrRock/OrrRock/Models/Enums/GymSettingModel.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/ExportCardView.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/HistoryView.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/HomeGymChartView.swift
  OrrRock/OrrRock/MyActivity/SwiftUIChartView/MyCardView.swift
  OrrRock/OrrRock/MyActivity/View/FirstDateSettingViewController.swift
  OrrRock/OrrRock/OnBoarding/OnBoardigSuperViewController.swift
  OrrRock/OrrRock/OnBoarding/OnBoardingViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteFindingSectionViewController.swift
  OrrRock/OrrRock/RouteFinding/RouteModalViewController.swift
  OrrRock/OrrRock/Upload/DateSettingViewController.swift
  OrrRock/OrrRock/Upload/GymSettingViewController.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
  OrrRock/OrrRock/VideoDetail/DateEditViewController.swift
  OrrRock/OrrRock/VideoDetail/GymEditViewController.swift
  OrrRock/OrrRock/VideoDetail/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoCollection/VideoCollectionViewController.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 🧸Ruyha

#309 [#278] fix - 툴바 아이콘 이미지 변경 시 아이콘 밀림 현상 해결
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 👾Kkoma

#316 [#226] feat - 루트파인딩 핵심 기능 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/CoreData/RouteFinding/PageInfo.swift
  OrrRock/OrrRock/CoreData/RouteFinding/PointInfo.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RotueDataDraft_Archive.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteCoreDataDAO.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteDataDraft.swift
  OrrRock/OrrRock/CoreData/RouteFinding/RouteInformation+CoreDataProperties.swift
  OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController+UICollectionViewExtensions.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController+UIPageViewExtensions.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingFeatureViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageView.swift
  OrrRock/OrrRock/RouteFindingFeature/RouteFindingPageViewController.swift
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureButton.swift
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureFootButton.swift
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureHandButton.swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController+UICollectionViewExtensions.swift .swift
  OrrRock/OrrRock/SaveRootFinding/RouteFindingSaveViewController.swift
  OrrRock/OrrRock/SceneDelegate.swift
Labels: feat

#318 [#317] HOTFIX - 핫픽스 코드 수정
  OrrRock/OrrRock/RouteFindingFeature/UIComponents/RouteFindingFeatureButton.swift
Labels: hotfix, 💡LED

#319 [#315] style - 앱 Alert 문구 수정 및 버튼 디테일 사항 반영
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/Enums/GymSettingModel.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: style, design, 🎵EllyJ

#322 [#279] fix - 비디오 디테일뷰 플레이스 홀더 버그 해결
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView+Protocol.swift
  OrrRock/OrrRock/VideoDetail/UIComponent/View/VideoInfoView.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailPageViewController/VideoDetailPageViewController+Extentions.swift
  OrrRock/OrrRock/VideoDetail/VideoDetailViewController/VideoDetailViewController.swift
Labels: fix, 🌝Dodo

#324 [#323] fix - 루트파인딩 메인 뷰 textalignment 수정
  OrrRock/OrrRock/RouteFinding/RouteModalViewController.swift
Labels: fix, 🌝Dodo

#325 [#320] fix - 카메라 사용권한 체크 후 refresh 이슈 + 부가적으로 발견된 카메라 관련 오류
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController+PHPickerViewControllerDelegate.swift
  OrrRock/OrrRock/RouteFindingUpload/RouteFindingCameraViewController.swift
Labels: fix, 🎵EllyJ

#326 [#313] fix - videoSlider
  OrrRock/OrrRock/Extensions/Color+.swift
  OrrRock/OrrRock/Upload/LevelAndPFSettingViewController.swift
Labels: fix, 🧸Ruyha
