Repository DeveloperAcademy-POSTECH/MacC-TEAM-8bit, pull requests merged in 2022-10, with the labels that each got.

#5 [#4] HotFix - gitignore 누락된 항목 추가
  .gitignore
  OrrRock/OrrRock/Models/Model
  OrrRock/OrrRock/ViewController.swift
Labels: hotfix, 👾Kkoma

#6 [feat] #3 HomeView UI 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCardCollectionViewThumbnailCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell+CollectionViewExtensions.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewHeaderCell.swift
Labels: feat, 💡LED

#13 [#9] feat - Core Data Model 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataClass.swift
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataProperties.swift
  OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
Labels: feat, 🎵EllyJ

#16 [#8] feat 디자이너(린다)와 함께 하는 디자인 가이드 파일 만들기
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/AppIcon.appiconset/Light.png
  OrrRock/OrrRock/Assets.xcassets/Colors/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRBlack.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray1.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray3.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray4.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray5.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRPass.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRUPBlue.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRWhite.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/orFail.colorset/Contents.json
  OrrRock/OrrRock/Extensions/Color+.swift
  OrrRock/OrrRock/Extensions/Padding+.swift
Labels: feat, 🧸Ruyha

#20 [#14] feat - CoreDataManager 구현: CREAT
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
  OrrRock/OrrRock/Models/CoreData/VideoInfo.swift
Labels: feat, 🎵EllyJ

#18 [#17] feat - HomeVeiwController에 기존 로직 추가
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
Labels: feat, 🧸Ruyha

#19 [#10] feat - HomeView 목록형 UI 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewFooterCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewHeaderCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
Labels: feat, 💡LED

#23 [#22] fix - 컬러명을 수정
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray2.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray3.colorset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Colors/oRGray4.colorset/Contents.json
  OrrRock/OrrRock/Extensions/Color+.swift
Labels: fix, 🧸Ruyha

#24 [#11] feat - VideoCollectionView 의 컬렉션 뷰 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/Views/VideoCollectionView/BasePaddingLabel.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VIdeoCollectionFooterCell.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewHeaderCell.swift
Labels: feat, 🌝Dodo

#30 [#15] feat - CoreDataManager 구현: READ
  OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
Labels: feat, 🎵EllyJ

#29 [#27] fix 네비게이션 바 숨기기 부작용 및 기존 로직 수정
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
Labels: fix, 🧸Ruyha

#25 [#7] feat - UIView의 좌, 우 Swipe 기능을 구현합니다.
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/dummy/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/gorilla.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/gorilla.imageset/gorilla.png
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/Views/UploadView/SwipeCardView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeCardViewController.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView/SwipeCardView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView/SwipeViewController.swift
Labels: feat, 🦒Ian, 🍒Yeni

#32 [#28] feat - HomeView QuickAction UI 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/VideoFilterEnum.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
Labels: feat, 💡LED

#36 [#35] feat - String타입과 Date타입간의 빈번한 데이터 포매팅에 대한 함수 작성
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Date+.swift
  OrrRock/OrrRock/Extensions/String+.swift
Labels: feat, 👾Kkoma

#34 [#33] design - HomeView 디자인 디테일 작업
  OrrRock/OrrRock/Assets.xcassets/Symbols/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock 1.png
  OrrRock/OrrRock/Assets.xcassets/Symbols/orrrock_logo.imageset/orrrock.png
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCardCollectionViewThumbnailCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewFooterCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewHeaderCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
Labels: design, 💡LED

#39 [#31] feat - Data Filtering 기능 추가
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/TestExtensions/Date+RandomDate.swift
  OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
  OrrRock/OrrRock/Models/CoreData/FilterOption.swift
  OrrRock/OrrRock/Models/CoreData/SortOption.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
Labels: feat, 🎵EllyJ

#37 [#12, #21] feat - Swipe 카드 내부에 목업 영상을 embed 한 후, [성공, 실패] 이미지를 Swipe 방향과 각도에 따라 이미지와 투명도를 변경합니다.
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/fail.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/fail.imageset/KakaoTalk_Photo_2022-10-22-22-51-51 1.png
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/success.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/SwipeableView/success.imageset/KakaoTalk_Photo_2022-10-22-22-51-52 2.png
  OrrRock/OrrRock/Assets.xcassets/dummy/gorilla.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/gorilla.imageset/gorilla.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/gorilla.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/gorilla.imageset/gorilla.png
  OrrRock/OrrRock/Assets.xcassets/dummy/video/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/video/ianIsComming.dataset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/video/ledIscomming.dataset/Contents.json
  OrrRock/OrrRock/Views/UploadView/SwipeCardView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeCardViewController.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView/SwipeCardView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeView/SwipeViewController.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardVideoView.swift
  OrrRock/OrrRock/Views/UploadView/SwipeableCardViewController.swift
Labels: feat, 🦒Ian, 🍒Yeni

#42 [#26] feat 영상 업로드 이전 과정 뷰 제작 및 코드 이주
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Extensions/Button+.swift
  OrrRock/OrrRock/Utils/CustomIndicator.swift
  OrrRock/OrrRock/Utils/UnderlinedTextField.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
  OrrRock/OrrRock/Views/UploadView/DateSettingViewController.swift
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: fix, 🧸Ruyha

#43 [#11] feat - VideoCollectionView의 UI완성
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewCustomCell.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewHeaderCell.swift
Labels: feat, 🐓Dodo

#53 [#49] feat - 선택된 영상의 localIdentifier 를 넘기는 방식으로 코드를 수정합니다.
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
  OrrRock/OrrRock/Models/CoreData/VideoInfo.swift
  OrrRock/OrrRock/Ruyha/UploadTestViewController.swift
  OrrRock/OrrRock/Ruyha/UpoadTestNextViewController.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
  OrrRock/OrrRock/Views/UploadView/DateSettingViewController.swift
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: feat, fix, 🧸Ruyha

#52 [#38] feat - 영상 상세 뷰 작성
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
Labels: feat, 👾Kkoma

#54 [#47] feat - DateAndGymEditView UI 완성
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/DateAndGymEditViewController.swift
Labels: feat, 🐓Dodo

#57 [#48] LevelAndPFEditView UI 완성 및 VideoCollectionVIew 연결 완료
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/MainViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
Labels: feat, 🌝Dodo

#56 [#40] feat - CoreDataManager 구현: UPLOAD & DELETE
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Models/CoreData/CoreDataDAO.swift
  OrrRock/OrrRock/Models/CoreData/CoreDataManager.swift
  OrrRock/OrrRock/Models/CoreData/DataManager.swift
  OrrRock/OrrRock/Models/CoreData/DataRepository.swift
  OrrRock/OrrRock/Models/CoreData/OrderOption.swift
  OrrRock/OrrRock/Models/CoreData/RandomDataGenerator.swift
  OrrRock/OrrRock/Models/CoreData/SectionData.swift
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataClass.swift
  OrrRock/OrrRock/Models/CoreData/VideoInformation+CoreDataProperties.swift
  OrrRock/OrrRock/OrrRock.xcdatamodeld/OrrRock.xcdatamodel/contents
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController+.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+DataSorting.swift
Labels: feat, 🎵EllyJ

#61 [#60] fix - homeview 네비게이션 변경
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
Labels: fix, 🌝Dodo

#63 [#58] fix 프로젝트 셋팅
  .DS_Store
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/AppDelegate.swift
  OrrRock/OrrRock/Info.plist
  OrrRock/OrrRock/SceneDelegate.swift
  OrrRock/OrrRock/Views/UploadView/GymSettingViewController.swift
Labels: feat, fix, 🧸Ruyha

#65 [#44, #45] feat - HomeView 데이터 연결 및 UI 디테일 수정
  OrrRock/OrrRock/Extensions/String+.swift
  OrrRock/OrrRock/Models/CoreData/DataManager.swift
  OrrRock/OrrRock/Models/CoreData/DataRepository.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewFooterCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewHeaderCell.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewListCell.swift
Labels: feat, 💡LED

#67 [#66] feat - HomeView → 다른 View 데이터 전달 코드 구현
  OrrRock/OrrRock/Models/CoreData/SectionData.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
Labels: feat, 💡LED

#69 [#68] hotfix - CustomDetailButton 코드 수정
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController+.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/CRUDTestViewController.swift
  OrrRock/OrrRock/ViewControllers/TestViewController/SortTestViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/Views/HomeView/HomeCollectionViewCardCell.swift
Labels: hotfix, 💡LED

#70 [#46] feat - VideoCollectionView 데이터 연동 완료
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoCollectionView/VideoCollectionViewHeaderCell.swift
Labels: feat, 🌝Dodo

#73 [#55] feat - VideoDetailView의 디테일 작업
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
Labels: feat, 👾Kkoma

#78 [#71, #72, #76, #77] feat, hotfix - HomeView 로부터 디테일뷰까지의 데이터 플로우 연결 및 버그 해결
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController+CollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/DateAndGymEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/LevelAndPFEditViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+DataSorting.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionView+VideoCollectionViewExtensions.swift
  OrrRock/OrrRock/ViewControllers/VideoCollectionViewController/VideoCollectionViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
Labels: feat, fix, 🌝Dodo

#83 [#81] feat - Develop 해독 / HomeView 데이터 없을 때 Placeholder 구현
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
Labels: feat, 💡LED

#82 [#80] feat - onBoading 완성
  OrrRock/OrrRock.xcodeproj/project.pbxproj
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon1.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon1.imageset/􀢾.png
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon2.imageset/Contents.json
  OrrRock/OrrRock/Assets.xcassets/dummy/image/icon2.imageset/icon2.png
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/OnBoardingViewController/OnBoardingViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
Labels: feat, 🌝Dodo

#85 [#84] fix 데이터피커 기본 값 수정
  OrrRock/OrrRock/Views/UploadView/DateSettingViewController.swift
Labels: fix, 🧸Ruyha

#86 [#75] feat - 뷰간 데이터 넘기기 위한 로직 구현 작업
  OrrRock/OrrRock/ViewControllers/HomeViewController/HomeViewController.swift
  OrrRock/OrrRock/ViewControllers/VideoDetailViewController/VideoDetailViewController.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoInfoView.swift
  OrrRock/OrrRock/Views/VideoDetailView/VideoPlayView.swift
Labels: feat, 👾Kkoma

#93 [#92] fix Color fix
  OrrRock/OrrRock/Assets.xcassets/Colors/oRFail.colorset/Contents.json
  OrrRock/OrrRock/Views/UploadView/SwipeableCardView/SwipeableCardViewController.swift
Labels: fix, 🧸Ruyha
